
export enum GameMode {
  MENU = 'MENU',
  DIFFICULTY_SELECT = 'DIFFICULTY_SELECT', // New Difficulty Selection Screen
  INSTRUCTIONS = 'INSTRUCTIONS', // New Introduction Screen
  OVERWORLD = 'OVERWORLD',
  BATTLE = 'BATTLE',
  REWARD = 'REWARD',
  CHEST_REWARD = 'CHEST_REWARD',
  GAMEOVER = 'GAMEOVER',
  VICTORY = 'VICTORY', // New Victory Screen
  LOADING_LEVEL = 'LOADING_LEVEL',
  INTERMISSION = 'INTERMISSION', 
  QUIZ_RESULT = 'QUIZ_RESULT', 
  LEADERBOARD = 'LEADERBOARD',
  PAUSED = 'PAUSED', 
  STATUS = 'STATUS', // New Status Screen
  LIBRARY = 'LIBRARY', // New Grimoire/Help Screen
  SHOP = 'SHOP', // New Shop Screen
}

// Fix for React Three Fiber JSX elements
declare global {
  namespace JSX {
    interface IntrinsicElements {
      [elemName: string]: any;
    }
  }
  namespace React {
    namespace JSX {
      interface IntrinsicElements {
        [elemName: string]: any;
      }
    }
  }
}

export interface ImpactLogEntry {
  id: string;
  type: 'QUIZ';
  stage: number;
  timestamp: number;
  carbonValue: number;

  // Quiz specific
  question?: string;
  yourAnswer?: string;
  correctAnswer?: string;
  isCorrect?: boolean;
}

export type QuizDifficulty = 'EASY' | 'MEDIUM' | 'HARD';

export interface PlayerStats {
  level: number;
  xp: number;
  xpToNextLevel: number;
  hp: number;
  maxHp: number;
  attackPower: number;
  moveSpeed: number;
  dashCooldownTime: number; 
  maxWeaponSlots: number; // NEW FIELD
  unlockedWeapons: Record<string, number>;
  unlockedPassives: Record<string, number>;
  
  modifiers: {
    projectileCount: number;
    damage: number;
    area: number;
    cooldown: number;
    knockback: number; // Added Knockback modifier
  };

  enemiesKilled: number;
  totalDamage: number;
  lastDamageTime: number;
  
  // Sustainability Metrics
  quizDifficulty: QuizDifficulty; // New field
  correctAnswers: number;
  carbonSaved: number; // Currency (spendable)
  lifetimeCarbon: number; // Score (Total accumulated)
  impactHistory: ImpactLogEntry[]; // Unified history log
  rerollCount: number; // Tracks number of rerolls for scaling cost
  
  // Shop Tracking
  statUpgrades: {
    hp: number;
    attack: number;
    speed: number;
  };
}

// Configuration generated by Gemini
export interface AiStageConfig {
  stageName: string;
  narrativeIntro: string;
  theme: {
    groundColor: string;
    checkColor: string;
    decoColor: string;
    borderColor: string;
    propType: string;
    landmarkType: string; // NEW: Controls the large voxel structure
  };
  enemies: {
    spawnPool: string[]; // Changed from primary/secondary to a pool
    speedMultiplier: number;
    hpMultiplier: number;
    densityMultiplier: number;
    damageMultiplier?: number; // Added for difficulty scaling
  };
  boss: {
    name: string;
    introductionLine: string;
    visualVariant: string;
    patternDifficulty: number;
    narrative: string; // NEW: Dramatic warning text
  };
  // NEW: Sustainability Quiz
  quiz: {
    question: string;
    options: {
      A?: string; // Optional for mid-stage quizzes
      B?: string; 
      C?: string; 
    };
    correctOption: 'A' | 'B' | 'C'; 
    explanation: string;
    impactValue: number; // Estimated kg of CO2 saved
  }
}

export interface AdviceResult {
  recommendedOptionId: string;
  reason: string;
}

export interface HighScore {
  name: string;
  stage: number;
  kills: number;
  damage: number;
  carbonSaved: number;
  date: number;
}

export interface UpgradeOption {
  id: string;
  type: 'STAT' | 'WEAPON' | 'PASSIVE';
  key: string; 
  label: string;
  description: string;
  icon: string;
  value?: number;
  isNewWeapon?: boolean;
  isEvolution?: boolean; 
  evolutionHint?: string;
  cost?: number; // CO2 Cost for Shop
}

export interface XpOrb {
  id: string;
  x: number;
  z: number;
  value: number;
  type: 'CO2_ORB'; // Renamed from XP_ORB
}

export interface Chest {
  id: string;
  x: number;
  z: number;
  isOpen: boolean;
}

export interface Enemy {
  id: string;
  x: number;
  z: number;
  hp: number;
  maxHp: number;
  type: 'TOXIC_SLIME' | 'MUTATED_BAT' | 'RUSTY_AUTOMATON' | 'GAS_CLOUD' | 'LANDFILL_GOLEM' | 'BOSS' | 
        'MUTATED_RAT' | 'PAPER_WASTE' | 'TOXIC_TOAD' | 'MUD_GOLEM' | 'DRONE' | 'MECH' | 
        'OIL_BLOB' | 'SLUDGE_HORROR' | 'PLASTIC_VULTURE' | 'RADIOACTIVE_SPIRIT' | 'SMOG_IMP' | 'SCRAP_KNIGHT' |
        'PLASTIC_BAG' | 'E_WASTE' | 'OIL_BARREL' | 'TRASH_CAN' | 'OLD_TIRE' | 'PLASTIC_BOTTLE';
  speed: number;
  attackRange: number;
  damage: number;
  name?: string; 
  visualVariant?: string; // NEW: Visual style override
  taunt?: string;
  lastHit?: number;
  attackCooldown?: number;
  dashCooldown?: number;
  facing?: number;
  dashTime?: number;
  dashVector?: { x: number, z: number };
  knockbackX?: number; // Physics for knockback X
  knockbackZ?: number; // Physics for knockback Z
  
  // Boss Movement State
  movementPhase?: 'CHASE' | 'DASH' | 'TELEPORT' | 'ORBIT';
  opacity?: number;
  teleportState?: 'IDLE' | 'TELEGRAPH' | 'FADEOUT' | 'FADEIN';
  teleportTimer?: number;
}

export interface Projectile {
  id: string;
  x: number;
  z: number;
  vx: number;
  vz: number;
  damage: number;
  fromPlayer: boolean;
  color: string;
  life: number;
  initialLife?: number; // Added for Arc calculation
  type?: 'NORMAL' | 'ORBITAL' | 'THUNDER' | 'HOMING' | 'STATIONARY' | 'MELEE' | 'BEAM';
  variant?: 'MAGIC_MISSILE' | 'AXE' | 'ENEMY_NORMAL' | 'BOSS_NORMAL' | 'FIREBALL' | 'ICE_SHARD' | 'POISON_BLOB' | 'CROSS' | 'DAGGER' | 'MAGIC_ARROW' | 'TECH_BEAM' | 'VOID_ORB' | 'FLAMETHROWER' | 'FIRE_MORTAR' | 'LAVA_POOL' | 'TOXIC_FLASK' | 'POISON_CLOUD' | 'JAVELIN' | 'CHAIN_LIGHTNING' | 'SPEAR' | 'SLIME_BALL' | 'SHURIKEN' | 'BIBLE' | 'KATANA' | 'TOXIN_GUN' | 'HOLY_BEAM' | 'PLAGUE_SPREADER' | 'TESLA_COIL';
  orbitAngle?: number; 
  returnTime?: number; 
  pierce?: number; // How many enemies it can hit
  bouncesLeft?: number; // NEW: Slime ball physics
  turnsLeft?: number; // NEW: Javelin chain logic
  hitList?: string[]; // NEW: To avoid hitting the same enemy in a chain
  knockbackValue?: number; // Snapshot of knockback power at spawn
}

export interface Vector2 {
  x: number;
  y: number;
}

export interface Portal {
  id: string;
  x: number;
  z: number;
  level: number;
  type: 'NORMAL' | 'BOSS';
  quizOption?: 'A' | 'B' | 'C'; // New field to link portal to answer
  colorOverride?: string;
}

export interface ActiveBattleState {
  portalId: string;
  level: number;
  isBoss: boolean;
  isBonus: boolean; // New field for correct answer reward
}